version: '3.3'

services:

  front-admin:
    build:
      context: ../front-admin/
      dockerfile: Dockerfile
    volumes:
      - '../front-admin:/app'
      - '../front-admin/app/node-modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  pastorais:
    image: pastorais
    restart: always
    ports:
      - '8080:8080'

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    I might not need a port configuration here because the docker-compose
#    already allows the other containers to access postgres' default CONTAINER_PORT, right?
    ports:
      - '8081:5432'

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  init-kafka:
    image: docker.io/bitnami/kafka:3
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics.sh --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic pastorais --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server kafka:9092 --list
      "

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
