version: '3.3'

services:

  reverseproxy:
    build:
      context: ../reverseproxy
      dockerfile: Dockerfile
    volumes:
      - '~/certs:/etc/nginx/certs'
    ports:
      - 80:3000
      - 443:443
      - 8888:8888
      - 9090:9090
    restart: always

#  front-admin-prod:
#    depends_on:
#      - reverseproxy
#    image: front-admin-prod
#    restart: always

  front-admin:
    depends_on:
      - reverseproxy
    build:
      context: ../front-admin/
      dockerfile: Dockerfile
      args:
        REACT_APP_IPMOSAICO_ROOT_URL: ${REACT_APP_IPMOSAICO_ROOT_URL}
    volumes:
      - '../front-admin:/app'
      - '../front-admin:/app/node-modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NGINX_PORT=3000

  gateway:
    depends_on:
      - reverseproxy
    image: gateway
    environment:
      - IPMOSAICO_ALLOW_HOST=${IPMOSAICO_ALLOW_HOST}
    restart: always

  comunicacao:
    image: comunicacao
    environment:
      - ONE_SIGNAL_APP_ID=${ONE_SIGNAL_APP_ID}
      - ONE_SIGNAL_APP_KEY=${ONE_SIGNAL_APP_KEY}
    depends_on:
      - kafka
    restart: always

  db-pastorais:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  pastorais:
    image: pastorais
    depends_on:
      - db-pastorais
      - kafka
    restart: always

  db-financeiro:
    build:
      context: ./db-financeiro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  financeiro:
    image: financeiro
    depends_on:
      - db-financeiro
      - kafka
    restart: always

  db-eventos:
    build:
      context: ./db-eventos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  eventos:
    image: eventos
    depends_on:
      - db-eventos
      - kafka
    restart: always

  db-compromissos:
    build:
      context: ./db-compromissos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  compromissos:
    image: compromissos
    depends_on:
      - db-compromissos
      - kafka
    restart: always

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

  init-kafka:
    image: docker.io/bitnami/kafka:3
    restart: always
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics.sh --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic novas-pastorais --replication-factor 1 --partitions 1
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic lembretes-pastorais --replication-factor 1 --partitions 1
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic novo-relatorio-financeiro --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server kafka:9092 --list
      "

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
